d3js: work around a conflict with the html directory
The build failed with an error about conflicting installation of the www
document root:

Running transaction test
Error: Transaction check error:
  file /srv/taloLogger/graph/html conflicts between attempted installs of talologgergraph-1.2c-r0.0.cortexa7hf_neon_vfpv4 and d3js-3.5.12-r0.3.cortexa7hf_neon_vfpv4

It is redundant to install the directory separately but this resolves
the error until the root cause is known and can be fixed properly.

Signed-off-by: Hannu Lounento <hannu.lounento@iki.fi>